### KAFKA ###
# max.poll.interval.ms=300000 (default)
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          headers: eventType
      #        bindings:
      #          message:
      #            consumer:
      #               enableDlq: true
      bindings:
        message:
          consumer:
            backOffInitialInterval: 1000
            backOffMaxInterval: 20000
            maxAttempts: 3
          group: message-service
          contentyType: application/json
          destination: events.message
